name: Feature Request
description: Suggest an enhancement.
title: "feat: "
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      placeholder: "What problem are you trying to solve?"
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed Solution
      placeholder: "Describe the desired behavior/UX."
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      placeholder: "Any alternative approaches?"